import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/navbar';
import Footer from '@/components/footer';
import Dynamicbg from '@/components/dynamicbg';
import VisitorNavbar from '@/components/visitornavbar';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <Dynamicbg/>
        <Navbar/>
        {/* <VisitorNavbar/> */}
        {children}
        <Footer/>
      </body>
    </html>
  );
}
